from app.models import db, Comment


# Adds a demo user, you can add other users here if you want
def seed_comments():
    c1 = Comment(content="Classic Potter. Breaks the law and the Minister of Magic comes to save him. Could this country be more corrupt?", user_id=7, post_id=1)
    c2 = Comment(content="Yeah, the Malfoys have NEVER gotten away with anything illegal...", user_id=3, post_id=1)
    c3 = Comment(content="Shut up Weasel. We all know YOUR family couldn't weasel your way out of a broomstick violation", user_id=7, post_id=1)
    c4 = Comment(content="Hermione! How are you taking so many classes!? It literally doesn't make any sense!", user_id=3, post_id=5)
    c5 = Comment(content="I told you! I'm just studying really hard!", user_id=2, post_id=5)
    c6 = Comment(content="@DEAN There is! But it's restricted and you'll need a ministry official to administer it. I think the guy would have to agree but I'm not sure. Let me check the library and get back to you!", user_id=2, post_id=2)
    c7 = Comment(content="I hope she stays safe. Not even aurors are safe from the worst Death Eaters.", user_id=5, post_id=3)
    c8 = Comment(content="Neville, that's LITERALLY impossible! I HAVE to see it!", user_id=15, post_id=4)
    c9 = Comment(content="Back off Pansy! Hannah is awesome. ", user_id=5, post_id=6)
    c10 = Comment(content="You're a terrible person!", user_id=17, post_id=6)
    c11 = Comment(content="lulz", user_id=1, post_id=7)
    c12 = Comment(content="@malfoy he wont be laffing after what we haveplanned for tomorow hahaah", user_id=8, post_id=7)
    c13 = Comment(content="@crabby Why would you write that on here, you COMPLETE MORON", user_id=7, post_id=7)
    c14 = Comment(content="whatd i do?", user_id=8, post_id=7)
    c15 = Comment(content="Oh really? That sounds pretty dangerous. I definitely wouldn't want to mess around with that.", user_id=2, post_id=8)
    c16 = Comment(content="hahahaha meow lol", user_id=3, post_id=8)
    c17 = Comment(content="At least we're safe at Hogwarts.", user_id=1, post_id=9)
    c18 = Comment(content="Why are you doing anything about it Potter? Too scared?", user_id=7, post_id=9)
    c19 = Comment(content="I'm not an auror. Why would I do something about it?", user_id=1, post_id=9)
    c20 = Comment(content="Your stupidity and ignorance are actually mind boggling", user_id=7, post_id=9)
    c21 = Comment(content="It was so interesting!", user_id=2, post_id=10)
    c22 = Comment(content="A fantastic class!", user_id=12, post_id=10)
    c23 = Comment(content="I'm in. After dinner in the History classroom? We can throw things through Binns lol", user_id=16, post_id=11)
    c24 = Comment(content="Zacharias! You should be more respectful! He's both dead and your professor!", user_id=2, post_id=11)
    c25 = Comment(content="Meh, he doesn't care", user_id=16, post_id=11)
    c26 = Comment(content="It's ok", user_id=3, post_id=14)
    c27 = Comment(content="I really like it", user_id=9, post_id=14)
    c28 = Comment(content="Amen", user_id=19, post_id=15)
    c29 = Comment(content="Excuse us for having lives", user_id=11, post_id=15)
    c30 = Comment(content="Who are you?", user_id=7, post_id=15)

    db.session.add(c1)
    db.session.add(c2)
    db.session.add(c3)
    db.session.add(c4)
    db.session.add(c5)
    db.session.add(c6)
    db.session.add(c7)
    db.session.add(c8)
    db.session.add(c9)
    db.session.add(c10)
    db.session.add(c11)
    db.session.add(c12)
    db.session.add(c13)
    db.session.add(c14)
    db.session.add(c15)
    db.session.add(c16)
    db.session.add(c17)
    db.session.add(c18)
    db.session.add(c19)
    db.session.add(c20)
    db.session.add(c21)
    db.session.add(c22)
    db.session.add(c23)
    db.session.add(c24)
    db.session.add(c25)
    db.session.add(c26)
    db.session.add(c27)
    db.session.add(c28)
    db.session.add(c29)
    db.session.add(c30)

    db.session.commit()


def undo_comments():
    db.session.execute('TRUNCATE users RESTART IDENTITY CASCADE;')
    db.session.commit()
