"""posts and comments

Revision ID: 2ab48952ea13
Revises: ffdc0a98111c
Create Date: 2022-02-15 15:06:22.258524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab48952ea13'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('house', sa.String(length=16), nullable=False))
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('bio', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('pic', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'pic')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'year')
    op.drop_column('users', 'house')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_table('comments')
    op.drop_table('posts')
    # ### end Alembic commands ###
