"""empty message

Revision ID: b8f361c6c438
Revises: b5a0533497a6
Create Date: 2022-02-17 12:38:02.308181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f361c6c438'
down_revision = 'b5a0533497a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
